#ifndef USER_INPUT_BINARY_NUMBERS_H_INCLUDED
#define USER_INPUT_BINARY_NUMBERS_H_INCLUDED

//FOR THE FIRST BINARY NUMBER ENTERED BY USER
void first_Binary(int arr[]);

//FOR THE SECOND BINARY NUMBER ENTERED BY USER
void second_Binary(int arr[]);

#endif // USER_INPUT_BINARY_NUMBERS_H_INCLUDED
